/**
 * Runtime configuration contract (plan §3, §3.3, T1.1). The same built
 * bundle boots in all three deployment modes (Bun mount, Service Worker,
 * standalone/cross-origin) by reading this config from the
 * `<script type="application/json" id="weft-console-config">` block
 * `index.html` injects, instead of baking a base URL in at build time.
 */
import type { WorkflowEventTransport } from '@lostgradient/weft/client';

const CONFIG_ELEMENT_ID = 'weft-console-config';

const EVENT_TRANSPORTS = ['auto', 'websocket', 'sse'] as const;

/**
 * Shape of the JSON runtime-config block. `baseUrl: ''` means "same
 * origin" (the Bun-mount and standalone-same-origin deployment modes);
 * Service Worker mode sets it to the SW's `pathPrefix` (plan §3.3), e.g.
 * `/weft`.
 */
export interface WeftConsoleRuntimeConfig {
  baseUrl: string;
  eventTransport?: WorkflowEventTransport;
  /** API key for `unauthenticatedAccess: 'reject'` deployments, held in memory only. */
  token?: string;
  /**
   * Extra headers sent on every request (plan §4: "Auth: `token`/`headers`
   * from config"), e.g. a fixed `X-API-Key` for a deployment that doesn't
   * use bearer tokens. Merged into `HttpClientOptions.headers`, so an
   * explicit `headers.Authorization` here wins over `token` (same precedence
   * `HttpClient` itself documents).
   */
  headers?: Record<string, string>;
  /**
   * Base URL the bundle's own hashed static assets are served from (plan
   * §3.1's "CDN deployments" case). Not consumed by `./client.ts` — it is a
   * static-asset-loading concern for whichever mount wires up `<base>`/asset
   * URLs, kept here because this module is the single place that reads the
   * injected config block.
   */
  assetBase?: string;
}

function isEventTransport(value: unknown): value is WorkflowEventTransport {
  return (EVENT_TRANSPORTS as readonly unknown[]).includes(value);
}

function isOptionalString(value: unknown): value is string | undefined {
  return value === undefined || typeof value === 'string';
}

function isOptionalStringRecord(value: unknown): value is Record<string, string> | undefined {
  if (value === undefined) return true;
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;
  return Object.values(value).every((entry) => typeof entry === 'string');
}

function isRuntimeConfig(value: unknown): value is WeftConsoleRuntimeConfig {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;

  if (typeof candidate['baseUrl'] !== 'string') return false;
  if (!isOptionalString(candidate['token'])) return false;
  if (!isOptionalString(candidate['assetBase'])) return false;
  if (!isOptionalStringRecord(candidate['headers'])) return false;
  if (candidate['eventTransport'] !== undefined && !isEventTransport(candidate['eventTransport'])) {
    return false;
  }

  return true;
}

/**
 * Reads and validates the injected runtime config. Falls back to same-origin
 * `auto` transport when the config script is missing or empty (e.g. a bare
 * `index.html` load outside any of the three documented mount modes).
 *
 * A *present* config block that fails to parse or fails shape validation
 * throws rather than silently falling back — that block is generated by the
 * mount (`weftConsole()`, the Service Worker host page, or a standalone
 * deployment's template), so a malformed one is a deployment bug worth
 * surfacing loudly, not masking with defaults.
 */
export function readRuntimeConfig(doc: Document = document): WeftConsoleRuntimeConfig {
  const element = doc.getElementById(CONFIG_ELEMENT_ID);
  const text = element?.textContent?.trim();

  if (!text) return { baseUrl: '', eventTransport: 'auto' };

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    throw new Error(`weft-console: #${CONFIG_ELEMENT_ID} did not contain valid JSON: ${reason}`, {
      cause: error,
    });
  }

  if (!isRuntimeConfig(parsed)) {
    throw new Error(
      `weft-console: #${CONFIG_ELEMENT_ID} did not contain a valid runtime config object`,
    );
  }

  return parsed;
}
